### ISSUE TITLE
Error on Truffle Migrate - Error: Error: TypeError: rs.setController is not a function

### ISSUE THREAD

**Issue by jyap808** [gointollc/etherep-contracts#4]
Error:
```
$ truffle migrate

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.


Starting migrations...
======================
> Network name:    'development'
> Network id:      1565049600687
> Block gas limit: 0x6691b7


2_deploy_etherep.js
===================

   Deploying 'RatingStore'
   -----------------------
   > transaction hash:    0x4b8da6ed423e360e9ddbc7a9de7163d665d95c087167fa87563c42ee4ed56362
   > Blocks: 0            Seconds: 0
   > contract address:    0xf763494fE934206253Fc433093a0a9432D72420c
   > block number:        1
   > block timestamp:     1565049621
   > account:             0x3A91B51F4D6dB9a525AA9751B3cb2c9c8aE16597
   > balance:             99.98004914
   > gas used:            997543
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.01995086 ETH


   Deploying 'Etherep'
   -------------------
   > transaction hash:    0xc93c41b3330dd13b0c1956cfc75738681bc898df6d862a1b34a57e06fe826263
   > Blocks: 0            Seconds: 0
   > contract address:    0xedCcDC5F9671E964c5cF9B2cE8C8256b42212D6D
   > block number:        2
   > block timestamp:     1565049622
   > account:             0x3A91B51F4D6dB9a525AA9751B3cb2c9c8aE16597
   > balance:             99.95761968
   > gas used:            1121473
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.02242946 ETH

Error: Error: TypeError: rs.setController is not a function
    at Object.run (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.30 (core: 5.0.30)
Node v10.16.0
```

**Comment by mikeshultz** [comment]
Thanks for raising the issue.  Might be a few days until I can get to this, but if you're itching to get it done, it looks like a problem with the migration script.  web3 has probably been moved to 1.0 now, so `rs.setController()` should be `rs.methods.setController()`(and every other contract call for that matter).

**Comment by jyap808** [comment]
That gives error:
```
Error: Error: TypeError: Cannot read property 'setController' of undefined
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.26 (core: 5.0.26)
Node v10.16.0
```
